#! /bin/bash

echo "Please enter your file name" 
read fileName

if [ -f $fileName ]
then 
echo "The file is exists, so you can write some data into it."
cat >> $fileName
else
echo "The file is not exists"
fi 
